spring.application.name=demo01
server.port=8080
frontend.url=${FRONTEND_URL}
paymentDraft=${PAYMENT_DETAIL_DRAFT_COLLECTION_NAME}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

javers.sqlDialect=POSTGRES
javers.sqlSchemaManagementEnabled=true
javers.algorithm=LEVENSHTEIN_DISTANCE
javers.commitIdGenerator=synchronized_sequence

spring.app.jwtSecret=${JWT_ACCESS_SECRET_KEY}
spring.app.jwtExpirationMs=900000
spring.app.jwt.refresh-expiration=604800000
spring.graphql.graphiql.enabled=true
spring.graphql.http.path=/api/graphql

server.forward-headers-strategy=framework


spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=${MONGO_USERNAME}
spring.data.mongodb.password=${MONGO_PASSWORD}
spring.data.mongodb.database=mindx
spring.data.mongodb.authentication-database=admin

spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${POSTGRESQL_USER}
spring.datasource.password=${POSTGRESQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.data.mongodb.uri=mongodb+srv://${CLUSTER_MONGO_USERNAME}:${CLUSTER_MONGO_PASSWORD}@${CLUSTER_MONGO_URI}/${CLUSTER_MONGO_DATABASE}?retryWrites=true&w=majority

spring.main.allow-bean-definition-overriding=true
spring.data.mongodb.auto-index-creation=true
spring.app.tempPassword=${TEMP_PASSWORD}
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS3_REGION}
aws.s3.bucketName=${AWS_S3_BUCKET_NAME}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB